spring.application.name=School-Management-Project
spring.datasource.username=W1_87109_Swaraj
spring.datasource.password=manager
spring.datasource.url=jdbc:mysql://localhost:3306/school_management?useSSL=false&serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

